// <auto-generated />
using System;
using HomeGroom.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeGroom.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20211125104612_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeGroom.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Cleaning"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Grooming"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Electrician"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Carpenter"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Plumber"
                        });
                });

            modelBuilder.Entity("HomeGroom.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateandTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            CategoryId = 1,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/electrician.jpg",
                            Price = 1500m,
                            ServiceName = "AC Repair"
                        },
                        new
                        {
                            ServiceId = 2,
                            CategoryId = 1,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/electrician.jpg",
                            Price = 1000m,
                            ServiceName = "Fridge Repair"
                        },
                        new
                        {
                            ServiceId = 3,
                            CategoryId = 1,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/electrician.jpg",
                            Price = 500m,
                            ServiceName = "Fan Repair"
                        },
                        new
                        {
                            ServiceId = 4,
                            CategoryId = 2,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/salon.jpg",
                            Price = 200m,
                            ServiceName = "Salon for Male"
                        },
                        new
                        {
                            ServiceId = 5,
                            CategoryId = 2,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/salon.jpg",
                            Price = 200m,
                            ServiceName = "Salon for female"
                        },
                        new
                        {
                            ServiceId = 6,
                            CategoryId = 2,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/salon.jpg",
                            Price = 500m,
                            ServiceName = "Massage"
                        },
                        new
                        {
                            ServiceId = 7,
                            CategoryId = 3,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/clean.jpg",
                            Price = 1000m,
                            ServiceName = "Pest Control"
                        },
                        new
                        {
                            ServiceId = 8,
                            CategoryId = 3,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/clean.jpg",
                            Price = 2000m,
                            ServiceName = "Room Cleaning"
                        },
                        new
                        {
                            ServiceId = 9,
                            CategoryId = 3,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/clean.jpg",
                            Price = 2000m,
                            ServiceName = "Kitchen Cleaning"
                        },
                        new
                        {
                            ServiceId = 10,
                            CategoryId = 3,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/clean.jpg",
                            Price = 2000m,
                            ServiceName = "Bathroom Cleaning"
                        },
                        new
                        {
                            ServiceId = 11,
                            CategoryId = 4,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/plumber.jpg",
                            Price = 1500m,
                            ServiceName = "Water Leakage"
                        },
                        new
                        {
                            ServiceId = 12,
                            CategoryId = 4,
                            DateandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "~/Images/plumber.jpg",
                            Price = 500m,
                            ServiceName = "Pipe Fixing"
                        });
                });

            modelBuilder.Entity("HomeGroom.Models.Service", b =>
                {
                    b.HasOne("HomeGroom.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeGroom.Models.Category", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
